lavalink:
    plugins:
        dunctebot:
            sources:
                clypit: true
                getyarn: true
                mixcloud: true
                ocremix: true
                pixeldrain: true
                pornhub: true
                reddit: true
                soundgasm: true
                tiktok: true
                tts: true
            ttsLanguage: en-AU
        lavasrc:
            providers:
                - ytsearch:"%ISRC%"
                - ytsearch:%QUERY%
            sources:
                spotify: true
                youtube: true
            spotify:
                albumLoadLimit: 6
                clientId: 8db85e4cfce8433bb7f80ce366b3373d
                clientSecret: 808decfe6312499699375bd4f9aea6df
                countryCode: ID
                resolveArtistsInSearch: true
                localFiles: false
                preferAnonymousToken: false
                customTokenEndpoint: http://localhost:8080/api/token
                playlistLoadLimit: 6
            youtube:
                countryCode: ID
                language: en
            ytdlp:
                path: "yt-dlp" # the path to the yt-dlp executable.
                searchLimit: 10
    server:
        bufferDurationMs: 400
        filters:
            channelMix: true
            distortion: true
            equalizer: true
            karaoke: true
            lowPass: true
            rotation: true
            timescale: true
            tremolo: true
            vibrato: true
            volume: true
        frameBufferDurationMs: 5000
        gc-warnings: true
        opusEncodingQuality: 10
        password: SatzzDev
        playerUpdateInterval: 5
        resamplingQuality: HIGH
        soundcloudSearchEnabled: true
        sources:
            bandcamp: true
            http: true
            nico: true
            soundcloud: true
            twitch: true
            vimeo: true
            youtube: false
        timeouts:
            connectTimeoutMs: 3000
            connectionRequestTimeoutMs: 3000
            socketTimeoutMs: 3000
        trackStuckThresholdMs: 10000
        useSeekGhosting: true
        youtubePlaylistLoadLimit: 6
        youtubeSearchEnabled: true
logging:
    file:
        path: ./logs/
    level:
        lavalink: INFO
        root: INFO
    logback:
        rollingpolicy:
            max-file-size: 1GB
            max-history: 30
    request:
        enabled: true
        includeClientInfo: true
        includePayload: true
        includeQueryString: true
        maxPayloadLength: 10000
server:
    address: 0.0.0.0
    http2:
        enabled: false
    port: 3886
