lavalink:
    plugins:
        - dependency: com.github.topi314.lavasrc:lavasrc-plugin:4.8.1
          repository: https://maven.lavalink.dev/releases
          snapshot: false
        - dependency: dev.lavalink.youtube:youtube-plugin:1.16.0
          repository: https://maven.lavalink.dev/releases
          snapshot: false
        - dependency: com.dunctebot:skybot-lavalink-plugin:1.5.1
          repository: https://maven.lavalink.dev/releases
          snapshot: false
        - dependency: net.esmbot:lava-xm-plugin:0.2.5
          repository: https://repo.projectlounge.pw/maven/releases
          snapshot: false
    pluginsDir: ./plugins
    server:
        bufferDurationMs: 400
        filters:
            channelMix: true
            distortion: true
            equalizer: true
            karaoke: true
            lowPass: true
            rotation: true
            timescale: true
            tremolo: true
            vibrato: true
            volume: true
        frameBufferDurationMs: 1000
        gc-warnings: true
        opusEncodingQuality: 10
        password: SatzzDev
        playerUpdateInterval: 5
        resamplingQuality: HIGH
        soundcloudSearchEnabled: true
        sources:
            bandcamp: true
            http: true
            local: false
            mixer: true
            soundcloud: true
            twitch: true
            vimeo: true
            youtube: false
        trackStuckThresholdMs: 10000
        useSeekGhosting: true
        youtubeConfig:
            email: ""
            password: ""
        youtubePlaylistLoadLimit: 6
        youtubeSearchEnabled: true
logging:
    file:
        path: ./logs/
    level:
        lavalink: INFO
        root: INFO
    logback:
        rollingpolicy:
            max-file-size: 1GB
            max-history: 30
    request:
        enabled: true
        includeClientInfo: true
        includeHeaders: false
        includePayload: true
        includeQueryString: true
        maxPayloadLength: 10000
metrics:
    prometheus:
        enabled: false
        endpoint: /metrics
plugins:
    dunctebot:
        sources:
            clypit: true
            getyarn: true
            mixcloud: true
            ocremix: true
            pornhub: true
            reddit: true
            soundgasm: true
            tiktok: true
            tts: true
        ttsLanguage: en-US
    lavasrc:
        applemusic:
            albumLoadLimit: 6
            countryCode: US
            mediaAPIToken: '...'
            playlistLoadLimit: 6
        deezer:
            masterDecryptionKey: your master decryption key
        flowerytts:
            audioFormat: mp3
            silence: 0
            speed: 1
            translate: false
            voice: default voice
        providers:
            - ytsearch:"%ISRC%"
            - ytsearch:%QUERY%
            - ytmsearch:"%ISRC%"
            - ytmsearch:%QUERY%
            - scsearch:%QUERY%
            - spsearch:%QUERY%
            - sprec:%QUERY%
            - amsearch:%QUERY%
            - dzisrc:%ISRC%
            - dzsearch:%QUERY%
            - ymsearch:%QUERY%
        sources:
            applemusic: false
            deezer: false
            flowerytts: false
            spotify: true
            yandexmusic: false
            youtube: true
        spotify:
            albumLoadLimit: 6
            clientId: 946221aed5ad4eaba9402eca103e70e8
            clientSecret: 776ae119f82a40508898f3d1ad7d9528
            countryCode: US
            playlistLoadLimit: 6
        yandexmusic:
            accessToken: your access token
        youtube:
            countryCode: US
    youtube:
        allowDirectPlaylistIds: true
        allowDirectVideoIds: true
        allowSearch: true
        clients:
            - MUSIC
            - ANDROID
            - WEB
            - TVHTML5EMBEDDED
        countryCode: US
        enabled: true
sentry:
    dsn: ""
    environment: ""
server:
    address: 0.0.0.0
    http2:
        enabled: false
    port: 80
